# Generated by Django 5.1.1 on 2024-09-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVPs', '0003_alunos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
