# Generated by Django 5.1.1 on 2024-09-13 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVPs', '0004_delete_entry_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_professor', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('contato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='alunos',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
