# Generated by Django 5.1.1 on 2024-09-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVPs', '0005_professores_projetos_alunos_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='MVPs.professores'),
        ),
    ]
